import type { DB, ID } from './types';

// Dates are generated relative to "today" so dashboards always show
// meaningful overdue / upcoming / trending data in the demo environment.
const now = new Date();
const d = (offsetDays: number) => {
  const t = new Date(now); t.setDate(t.getDate() + offsetDays);
  return t.toISOString().slice(0, 10);
};
const m = (offsetMonths: number) => {
  const t = new Date(now); t.setMonth(t.getMonth() + offsetMonths);
  return t.toISOString().slice(0, 7);
};
const ts = (offsetDays: number, h = 9) => {
  const t = new Date(now); t.setDate(t.getDate() + offsetDays); t.setHours(h, 24 - (offsetDays % 50), 0, 0);
  return t.toISOString();
};

export const ORG_PUB: ID = 'org-pref';
export const ORG_PRIV: ID = 'org-sys';

export function buildSeed(): DB {
  return {
    version: 3,
    organizations: [
      {
        id: ORG_PUB, name: 'Prefeitura Municipal de Exemplo', legalName: 'Município de Exemplo — Poder Executivo',
        taxId: '12.345.678/0001-90', type: 'Orgão Público', initials: 'PME', mainColor: '#0e7f75', secondaryColor: '#2a6691',
        timezone: 'America/Sao_Paulo', currency: 'BRL', fiscalYearStart: 1, workingDays: 'Segunda a Sexta',
        workingHours: '08h às 17h', sector: 'public',
        governance: { approvalLevels: 2, requiresCharter: true, evmEnabled: true, publicTerms: true },
      },
      {
        id: ORG_PRIV, name: 'Systenex Engenharia S.A.', legalName: 'Systenex Engenharia e Tecnologia S.A.',
        taxId: '98.765.432/0001-10', type: 'Empresa Privada', initials: 'SYS', mainColor: '#255376', secondaryColor: '#17998c',
        timezone: 'America/Sao_Paulo', currency: 'BRL', fiscalYearStart: 1, workingDays: 'Segunda a Sexta',
        workingHours: '09h às 18h', sector: 'private',
        governance: { approvalLevels: 1, requiresCharter: true, evmEnabled: true, publicTerms: false },
      },
    ],
    units: [
      { id: 'un-smi', orgId: ORG_PUB, name: 'Secretaria de Modernização e Inovação', kind: 'Secretaria' },
      { id: 'un-sop', orgId: ORG_PUB, name: 'Secretaria de Obras e Planejamento', kind: 'Secretaria' },
      { id: 'un-sfa', orgId: ORG_PUB, name: 'Secretaria da Fazenda', kind: 'Secretaria' },
      { id: 'un-sgs', orgId: ORG_PUB, name: 'Secretaria de Gestão e Segurança', kind: 'Secretaria' },
      { id: 'un-gab', orgId: ORG_PUB, name: 'Gabinete do Prefeito', kind: 'Unidade Administrativa' },
      { id: 'un-dir', orgId: ORG_PRIV, name: 'Diretoria de Operações', kind: 'Departamento' },
      { id: 'un-ti', orgId: ORG_PRIV, name: 'Tecnologia e Sistemas', kind: 'Business Unit' },
    ],
    roles: [
      { key: 'master', name: 'Administrador Master', description: 'Acesso total da plataforma (desenvolvimento).' },
      { key: 'org_admin', name: 'Administrador da Organização', description: 'Gerencia organização, usuários e configurações.' },
      { key: 'director', name: 'Diretor', description: 'Visão executiva e aprovações estratégicas.' },
      { key: 'secretary', name: 'Secretário', description: 'Gestão de secretaria e programas governamentais.' },
      { key: 'executive', name: 'Executivo', description: 'Acesso a painéis estratégicos e decisões.' },
      { key: 'portfolio_mgr', name: 'Gestor de Portfólio', description: 'Priorização, portfólios e programas.' },
      { key: 'program_mgr', name: 'Gerente de Programa', description: 'Coordena programas e projetos relacionados.' },
      { key: 'project_mgr', name: 'Gerente de Projeto', description: 'Planejamento e execução de projetos.' },
      { key: 'pmo', name: 'PMO', description: 'Governança, metodologia, relatórios e auditoria.' },
      { key: 'team_lead', name: 'Líder de Equipe', description: 'Gestão de equipes e entregas.' },
      { key: 'analyst', name: 'Analista', description: 'Análise de demandas e suporte ao PMO.' },
      { key: 'member', name: 'Membro de Equipe', description: 'Executa tarefas e atualiza progresso.' },
      { key: 'requester', name: 'Solicitante', description: 'Registra ideias e demandas.' },
      { key: 'auditor', name: 'Auditor', description: 'Consulta registros e trilhas de auditoria.' },
      { key: 'viewer', name: 'Visualizador', description: 'Acesso somente leitura.' },
    ],
    users: [
      { id: 'u-admin', orgId: ORG_PRIV, name: 'Administrador NEX', email: 'admin@systenex.local', role: 'master', position: 'Administrador Master', active: true, initials: 'AN', skills: ['Governança', 'Arquitetura'], capacityH: 40, mustChangePassword: true, isDevAccount: true },
      { id: 'u-mariana', orgId: ORG_PUB, name: 'Mariana Souza', email: 'mariana.souza@exemplo.gov.br', role: 'pmo', position: 'Coordenadora do PMO', unitId: 'un-smi', active: true, initials: 'MS', skills: ['Governança', 'EVM', 'Relatórios'], capacityH: 40 },
      { id: 'u-carlos', orgId: ORG_PUB, name: 'Carlos Lima', email: 'carlos.lima@exemplo.gov.br', role: 'project_mgr', position: 'Gerente de Projetos', unitId: 'un-smi', active: true, initials: 'CL', skills: ['Cronograma', 'TI', 'Ágil'], capacityH: 40 },
      { id: 'u-fernanda', orgId: ORG_PUB, name: 'Fernanda Alves', email: 'fernanda.alves@exemplo.gov.br', role: 'secretary', position: 'Secretária de Modernização', unitId: 'un-smi', active: true, initials: 'FA', skills: ['Estratégia', 'Governança'], capacityH: 40 },
      { id: 'u-joao', orgId: ORG_PUB, name: 'João Pereira', email: 'joao.pereira@exemplo.gov.br', role: 'analyst', position: 'Analista de Projetos', unitId: 'un-smi', active: true, initials: 'JP', skills: ['Análise', 'Dados'], capacityH: 40 },
      { id: 'u-marcos', orgId: ORG_PUB, name: 'Marcos Vieira', email: 'marcos.vieira@exemplo.gov.br', role: 'member', position: 'Técnico de Infraestrutura', unitId: 'un-smi', active: true, initials: 'MV', skills: ['Redes', 'Servidores'], capacityH: 40 },
      { id: 'u-ana', orgId: ORG_PUB, name: 'Ana Castro', email: 'ana.castro@exemplo.gov.br', role: 'requester', position: 'Diretora de Atendimento', unitId: 'un-gab', active: true, initials: 'AC', skills: ['Atendimento'], capacityH: 30 },
      { id: 'u-paulo', orgId: ORG_PUB, name: 'Paulo Reis', email: 'paulo.reis@exemplo.gov.br', role: 'auditor', position: 'Auditor Interno', unitId: 'un-sfa', active: true, initials: 'PR', skills: ['Auditoria', 'LGPD'], capacityH: 30 },
      { id: 'u-beatriz', orgId: ORG_PUB, name: 'Beatriz Nunes', email: 'beatriz.nunes@exemplo.gov.br', role: 'project_mgr', position: 'Engenheira — Gerente de Obras', unitId: 'un-sop', active: true, initials: 'BN', skills: ['Obras', 'Medições'], capacityH: 40 },
      { id: 'u-ricardo', orgId: ORG_PUB, name: 'Ricardo Teles', email: 'ricardo.teles@exemplo.gov.br', role: 'portfolio_mgr', position: 'Gestor de Portfólio', unitId: 'un-gab', active: true, initials: 'RT', skills: ['Portfólio', 'Priorização'], capacityH: 40 },
      { id: 'u-sys1', orgId: ORG_PRIV, name: 'Otávio Braga', email: 'otavio.braga@systenex.com', role: 'project_mgr', position: 'Gerente de Projetos', unitId: 'un-ti', active: true, initials: 'OB', skills: ['BIM', 'Automação'], capacityH: 40 },
      { id: 'u-sys2', orgId: ORG_PRIV, name: 'Lívia Ramos', email: 'livia.ramos@systenex.com', role: 'executive', position: 'Diretora de Operações', unitId: 'un-dir', active: true, initials: 'LR', skills: ['Estratégia'], capacityH: 40 },
    ],
    plans: [
      { id: 'plan-pref', orgId: ORG_PUB, name: 'Plano Estratégico 2025–2028', horizon: '2025–2028', pillars: [
        { id: 'pil-1', name: 'Cidade Inteligente', color: '#17998c' },
        { id: 'pil-2', name: 'Qualidade de Vida', color: '#2a6691' },
        { id: 'pil-3', name: 'Governança Exemplar', color: '#b45309' },
      ]},
      { id: 'plan-sys', orgId: ORG_PRIV, name: 'Planejamento Estratégico Systenex', horizon: '2025–2027', pillars: [
        { id: 'pil-s1', name: 'Excelência Operacional', color: '#255376' },
        { id: 'pil-s2', name: 'Inovação e Digital', color: '#17998c' },
      ]},
    ],
    objectives: [
      { id: 'oe-1', orgId: ORG_PUB, planId: 'plan-pref', pillarId: 'pil-1', code: 'OE-01', name: 'Transformação Digital dos Serviços Públicos', description: 'Digitalizar 100% dos serviços ao cidadão até 2027.', indicator: '% de serviços digitais', current: 42, goal: 100, unit: '%' },
      { id: 'oe-2', orgId: ORG_PUB, planId: 'plan-pref', pillarId: 'pil-2', code: 'OE-02', name: 'Infraestrutura Urbana Sustentável', description: 'Modernizar vias, drenagem e eficiência energética.', indicator: 'Índice de infraestrutura', current: 58, goal: 85, unit: '%' },
      { id: 'oe-3', orgId: ORG_PUB, planId: 'plan-pref', pillarId: 'pil-3', code: 'OE-03', name: 'Gestão Eficiente e Transparente', description: 'Reduzir tempo médio de processos administrativos em 50%.', indicator: 'Tempo médio de processo', current: 22, goal: 11, unit: 'dias' },
      { id: 'oe-4', orgId: ORG_PUB, planId: 'plan-pref', pillarId: 'pil-2', code: 'OE-04', name: 'Segurança e Bem-estar da População', description: 'Ampliar cobertura de monitoramento urbano.', indicator: 'Cobertura de monitoramento', current: 31, goal: 70, unit: '%' },
      { id: 'oe-s1', orgId: ORG_PRIV, planId: 'plan-sys', pillarId: 'pil-s2', code: 'OE-S1', name: 'Digitalização da Operação', description: 'Aumentar produtividade com BIM e automação.', indicator: 'ROI da carteira digital', current: 12, goal: 30, unit: '%' },
      { id: 'oe-s2', orgId: ORG_PRIV, planId: 'plan-sys', pillarId: 'pil-s1', code: 'OE-S2', name: 'Compliance e Integridade', description: 'Certificar sistemas de gestão até 2026.', indicator: 'Certificações ativas', current: 1, goal: 3, unit: '' },
    ],
    ideas: [
      {
        id: 'ide-1', orgId: ORG_PUB, code: 'IDE-2025-014', title: 'Atendimento ao cidadão via assistente virtual',
        description: 'Criar um assistente virtual integrado ao Portal do Cidadão para responder dúvidas frequentes, agendar serviços e protocolar solicitações 24h por dia.',
        problem: 'Central de atendimento sobrecarregada: tempo médio de espera de 14 minutos e 32% das ligações tratam de dúvidas simples.',
        benefit: 'Redução de até 40% do volume de chamadas e atendimento disponível 24/7.',
        area: 'Secretaria de Modernização e Inovação', audience: 'Cidadãos e servidores do atendimento', urgency: 'Alta',
        authorId: 'u-ana', status: 'Em Análise', createdAt: ts(-12), attachments: 2,
      },
      {
        id: 'ide-2', orgId: ORG_PUB, code: 'IDE-2025-015', title: 'Sensores de alagamento em pontos críticos',
        description: 'Instalar sensores de nível de água em 18 pontos críticos com alertas automáticos para a defesa civil.',
        problem: 'Alagamentos recorrentes no período de chuvas, com resposta tardia da defesa civil.',
        benefit: 'Alerta antecipado estimado em 45 minutos, redução de danos materiais.',
        area: 'Secretaria de Obras e Planejamento', audience: 'Defesa civil e população de áreas de risco', urgency: 'Alta',
        authorId: 'u-beatriz', status: 'Priorizada', createdAt: ts(-30), attachments: 1,
      },
      { id: 'ide-3', orgId: ORG_PUB, code: 'IDE-2025-016', title: 'Painel público de obras em tempo real', description: 'Publicar andamento físico e financeiro das obras em portal aberto, com fotos mensais.', problem: 'Falta de transparência gera reclamações e pedidos de informação (LAI).', benefit: 'Redução de pedidos LAI e aumento da confiança pública.', area: 'Secretaria de Obras e Planejamento', audience: 'População e órgãos de controle', urgency: 'Média', authorId: 'u-joao', status: 'Registrada', createdAt: ts(-5), attachments: 0 },
      { id: 'ide-4', orgId: ORG_PUB, code: 'IDE-2024-092', title: 'Digitalização do acervo de alvarás', description: 'Digitalizar 120 mil processos físicos de alvarás com OCR e indexação.', problem: 'Consultas a processos antigos levam até 15 dias.', benefit: 'Consulta em minutos e preservação do acervo.', area: 'Secretaria da Fazenda', audience: 'Fiscais e contribuintes', urgency: 'Baixa', authorId: 'u-paulo', status: 'Convertida em Demanda', createdAt: ts(-90), attachments: 3 },
      { id: 'ide-5', orgId: ORG_PRIV, code: 'IDE-S-101', title: 'Dashboards de obra via drone', description: 'Sobrevoos semanais com drone para gerar orthofotos e medir avanço físico automaticamente.', problem: 'Medições manuais demoram 3 dias e têm margem de erro alta.', benefit: 'Medição semanal com erro inferior a 2%.', area: 'Diretoria de Operações', audience: 'Gerentes de obra', urgency: 'Média', authorId: 'u-sys1', status: 'Registrada', createdAt: ts(-8), attachments: 0 },
    ],
    demands: [
      { id: 'dem-1', orgId: ORG_PUB, code: 'DEM-2025-087', title: 'Substituição de switches obsoletos do datacenter', description: 'Switches de núcleo com fim de suporte do fabricante; risco de indisponibilidade.', requesterId: 'u-marcos', unitId: 'un-smi', category: 'Infraestrutura de Rede', type: 'Melhoria', priority: 'Crítica', urgency: 'Alta', impact: 'Alto', effort: 'G', requestedAt: d(-41), desiredDate: d(30), analystId: 'u-joao', status: 'Em Análise', origin: 'Interna', benefit: 'Disponibilidade de rede 99,9%', justification: 'Fim de suporte do fabricante em 90 dias.' },
      { id: 'dem-2', orgId: ORG_PUB, code: 'DEM-2025-088', title: 'Expansão de wi-fi nas unidades de saúde', description: 'Cobertura wi-fi em 12 UBS para prontuário eletrônico.', requesterId: 'u-ana', unitId: 'un-gab', category: 'Infraestrutura de Rede', type: 'Expansão', priority: 'Alta', urgency: 'Alta', impact: 'Alto', effort: 'G', requestedAt: d(-38), desiredDate: d(60), analystId: 'u-joao', status: 'Em Análise', origin: 'Interna', benefit: 'Prontuário eletrônico em 100% das UBS', justification: 'Indisponibilidade de sistema durante atendimentos.' },
      { id: 'dem-3', orgId: ORG_PUB, code: 'DEM-2025-090', title: 'Link de internet redundante para escolas', description: 'Link reserva para 40 escolas municipais.', requesterId: 'u-ana', unitId: 'un-gab', category: 'Infraestrutura de Rede', type: 'Expansão', priority: 'Média', urgency: 'Média', impact: 'Médio', effort: 'M', requestedAt: d(-33), desiredDate: d(90), status: 'Triagem', origin: 'Interna', benefit: 'Continuidade pedagógica digital', justification: 'Quedas frequentes de link único.' },
      { id: 'dem-4', orgId: ORG_PUB, code: 'DEM-2025-091', title: 'Renovação da frota — veículos de fiscalização', description: 'Evento recebido do NEXFROTA: 6 veículos de fiscalização com manutenção acima do limite econômico.', requesterId: 'u-paulo', unitId: 'un-sgs', category: 'Frota', type: 'Substituição', priority: 'Alta', urgency: 'Média', impact: 'Médio', effort: 'M', requestedAt: d(-15), desiredDate: d(75), analystId: 'u-ricardo', status: 'Priorizada', origin: 'NEXFROTA', benefit: 'Redução de 35% do custo de manutenção', justification: 'Custo de manutenção 2,4x acima da média da frota.' },
      { id: 'dem-5', orgId: ORG_PUB, code: 'DEM-2025-093', title: 'Módulo de transparência de emendas', description: 'Publicar execução de emendas parlamentares em portal próprio.', requesterId: 'u-fernanda', unitId: 'un-gab', category: 'Transparência', type: 'Novo', priority: 'Alta', urgency: 'Alta', impact: 'Alto', effort: 'M', requestedAt: d(-20), desiredDate: d(45), analystId: 'u-joao', status: 'Aprovada', origin: 'Interna', benefit: 'Atendimento à Lei de Diretrizes Orçamentárias', justification: 'Obrigação legal com prazo no próximo exercício.' },
      { id: 'dem-6', orgId: ORG_PUB, code: 'DEM-2025-094', title: 'Treinamento de fiscais de contrato', description: 'Capacitar 60 fiscais e gestores de contratos administrativos.', requesterId: 'u-paulo', unitId: 'un-sfa', category: 'Capacitação', type: 'Capacitação', priority: 'Média', urgency: 'Baixa', impact: 'Médio', effort: 'P', requestedAt: d(-12), desiredDate: d(120), status: 'Nova', origin: 'Interna', benefit: 'Redução de apontamentos de auditoria', justification: 'Apontamentos recorrentes do controle interno.' },
      { id: 'dem-7', orgId: ORG_PUB, code: 'DEM-2024-141', title: 'Modernização do parque de impressão', description: 'Substituir impressoras por modelo de outsourcing com bilhetagem.', requesterId: 'u-marcos', unitId: 'un-smi', category: 'TI', type: 'Modernização', priority: 'Baixa', urgency: 'Baixa', impact: 'Baixo', effort: 'P', requestedAt: d(-120), analystId: 'u-joao', status: 'Convertida em Projeto', origin: 'Interna', benefit: 'Economia anual estimada de R$ 180 mil', justification: 'Custo de suprimentos acima do mercado.', relatedProjectId: 'prj-4' },
      { id: 'dem-8', orgId: ORG_PRIV, code: 'DEM-S-220', title: 'Integração ERP × BIM para medições', description: 'Automatizar medições de obra a partir de modelos BIM.', requesterId: 'u-sys1', unitId: 'un-ti', category: 'Automação', type: 'Integração', priority: 'Alta', urgency: 'Média', impact: 'Alto', effort: 'G', requestedAt: d(-25), analystId: 'u-sys1', status: 'Em Planejamento', origin: 'Interna', benefit: 'Medição 70% mais rápida', justification: 'Gargalo de medição nas 3 obras ativas.' },
    ],
    portfolios: [
      { id: 'pf-1', orgId: ORG_PUB, name: 'Portfólio Cidade Digital', description: 'Iniciativas de tecnologia, dados e serviços digitais.', ownerId: 'u-ricardo', objectiveIds: ['oe-1', 'oe-3'], budget: 14800000, riskProfile: 'Médio', priority: 1, status: 'Ativo' },
      { id: 'pf-2', orgId: ORG_PUB, name: 'Portfólio de Obras e Infraestrutura', description: 'Obras urbanas, drenagem e eficiência energética.', ownerId: 'u-beatriz', objectiveIds: ['oe-2', 'oe-4'], budget: 32500000, riskProfile: 'Alto', priority: 2, status: 'Ativo' },
      { id: 'pf-sys', orgId: ORG_PRIV, name: 'Portfólio Corporativo Systenex', description: 'Transformação digital e compliance da operação.', ownerId: 'u-sys2', objectiveIds: ['oe-s1', 'oe-s2'], budget: 8900000, riskProfile: 'Médio', priority: 1, status: 'Ativo' },
    ],
    programs: [
      { id: 'pgm-1', orgId: ORG_PUB, code: 'PGM-01', name: 'Programa Cidade Digital', objective: 'Integrar infraestrutura, dados e serviços digitais do município.', managerId: 'u-mariana', benefits: ['Serviços 100% digitais', 'Rede unificada com 99,9% de disponibilidade', 'Decisões baseadas em dados'], budget: 9600000, objectiveIds: ['oe-1'], status: 'Ativo', start: d(-220), end: d(420) },
      { id: 'pgm-2', orgId: ORG_PUB, code: 'PGM-02', name: 'Programa Infraestrutura Urbana', objective: 'Requalificação de vias e eficiência energética de prédios públicos.', managerId: 'u-beatriz', benefits: ['Redução de 28% no consumo energético', 'Índice de infraestrutura de 58 para 85'], budget: 21400000, objectiveIds: ['oe-2'], status: 'Ativo', start: d(-160), end: d(520) },
      { id: 'pgm-s1', orgId: ORG_PRIV, code: 'PGM-S1', name: 'Programa Transformação Digital Systenex', objective: 'Digitalizar medições e gestão de obras com BIM.', managerId: 'u-sys1', benefits: ['ROI estimado de 30%', 'Medições semanais automatizadas'], budget: 6200000, objectiveIds: ['oe-s1'], status: 'Ativo', start: d(-120), end: d(300) },
    ],
    projects: [
      {
        id: 'prj-1', orgId: ORG_PUB, code: 'PRJ-2025-001', name: 'Modernização da Infraestrutura de Rede',
        description: 'Substituição do núcleo de rede, switches de acesso e cabeamento em 14 prédios municipais.',
        objective: 'Elevar a disponibilidade da rede municipal para 99,9%.',
        justification: 'Equipamentos com fim de suporte e indisponibilidades crescentes.',
        sponsorId: 'u-fernanda', managerId: 'u-carlos', pmoId: 'u-mariana', teamIds: ['u-carlos', 'u-marcos', 'u-joao'],
        start: d(-150), plannedEnd: d(45), forecastEnd: d(63), priority: 'Crítica', status: 'Em Execução',
        objectiveIds: ['oe-1'], programId: 'pgm-1', portfolioId: 'pf-1', budget: 4200000,
        methodology: 'Híbrida', type: 'Tecnologia', confidentiality: 'Interno', unitId: 'un-smi', progress: 58,
        tags: ['infraestrutura', 'rede', 'datacenter'], createdAt: ts(-160), updatedAt: ts(-1),
        charter: { businessNeed: 'A rede municipal sustenta serviços críticos de saúde, educação e fazenda; o núcleo atual tem 11 anos.', scope: 'Núcleo, distribuição e acesso de 14 prédios; fora do escopo: rede das escolas (fase 2).', benefits: ['Disponibilidade 99,9%', 'Capacidade 10x', 'Suporte do fabricante por 5 anos'], deliverables: ['Novo núcleo de datacenter', '14 prédios comutados', 'Documentação as-built'], assumptions: ['Entrega de equipamentos em até 90 dias', 'Janelas de manutenção fora do expediente'], constraints: ['Orçamento congelado no exercício', 'Licitação concluída'], risks: ['Atraso de fornecedor', 'Indisponibilidade durante migração'], approvedBy: 'Fernanda Alves', approvedAt: d(-155) },
        scope: { inScope: ['Núcleo de datacenter', 'Switches de 14 prédios', 'Cabeamento certificado', 'Monitoramento'], outScope: ['Rede de escolas', 'Telefonia IP', 'Links de operadora'], deliverables: ['Núcleo ativo', 'Prédios migrados', 'As-built'] },
      },
      {
        id: 'prj-2', orgId: ORG_PUB, code: 'PRJ-2025-002', name: 'Portal do Cidadão 2.0',
        description: 'Novo portal com serviços digitais, agendamento e protocolo integrado.',
        objective: 'Ampliar serviços digitais de 42% para 70%.',
        justification: 'Fila presencial e baixa adesão ao portal atual.',
        sponsorId: 'u-fernanda', managerId: 'u-carlos', pmoId: 'u-mariana', teamIds: ['u-carlos', 'u-joao'],
        start: d(-110), plannedEnd: d(90), priority: 'Alta', status: 'Em Execução',
        objectiveIds: ['oe-1'], programId: 'pgm-1', portfolioId: 'pf-1', budget: 2800000,
        methodology: 'Ágil', type: 'Tecnologia', confidentiality: 'Público', unitId: 'un-smi', progress: 66,
        tags: ['portal', 'cidadão', 'ágil'], createdAt: ts(-115), updatedAt: ts(-2),
      },
      {
        id: 'prj-3', orgId: ORG_PUB, code: 'PRJ-2025-003', name: 'Requalificação da Av. Central',
        description: 'Recapeamento, drenagem, calçadas acessíveis e ciclovia de 4,2 km.',
        objective: 'Elevar o índice de infraestrutura urbana e a segurança viária.',
        justification: 'Via com maior índice de acidentes e reclamações de drenagem.',
        sponsorId: 'u-fernanda', managerId: 'u-beatriz', pmoId: 'u-mariana', teamIds: ['u-beatriz', 'u-marcos'],
        start: d(-240), plannedEnd: d(30), forecastEnd: d(48), priority: 'Crítica', status: 'Em Execução',
        objectiveIds: ['oe-2'], programId: 'pgm-2', portfolioId: 'pf-2', budget: 12600000,
        methodology: 'Preditiva', type: 'Obras', confidentiality: 'Público', unitId: 'un-sop', progress: 71,
        tags: ['obras', 'drenagem', 'ciclovia'], createdAt: ts(-250), updatedAt: ts(-1),
      },
      {
        id: 'prj-4', orgId: ORG_PUB, code: 'PRJ-2025-004', name: 'Processo Administrativo Eletrônico',
        description: 'Digitalização de fluxos administrativos com assinatura eletrônica e tramitação 100% digital.',
        objective: 'Reduzir o tempo médio de processo de 22 para 11 dias.',
        justification: 'Tramitação física lenta e risco de extravio.',
        sponsorId: 'u-fernanda', managerId: 'u-carlos', teamIds: ['u-carlos', 'u-joao', 'u-ana'],
        start: d(-80), plannedEnd: d(140), priority: 'Alta', status: 'Em Execução',
        objectiveIds: ['oe-3'], portfolioId: 'pf-1', budget: 1900000,
        methodology: 'Híbrida', type: 'Modernização', confidentiality: 'Interno', unitId: 'un-smi', progress: 34,
        tags: ['processos', 'assinatura digital'], createdAt: ts(-85), updatedAt: ts(-4),
      },
      {
        id: 'prj-5', orgId: ORG_PUB, code: 'PRJ-2025-005', name: 'Videomonitoramento Inteligente',
        description: 'Ampliação de câmeras com analíticos de vídeo integrados ao centro de operações.',
        objective: 'Ampliar cobertura de monitoramento de 31% para 55%.',
        justification: 'Plano municipal de segurança e demanda da população.',
        sponsorId: 'u-fernanda', managerId: 'u-beatriz', pmoId: 'u-mariana', teamIds: ['u-beatriz', 'u-marcos'],
        start: d(-60), plannedEnd: d(180), priority: 'Média', status: 'Planejamento',
        objectiveIds: ['oe-4'], programId: 'pgm-1', portfolioId: 'pf-2', budget: 5400000,
        methodology: 'Preditiva', type: 'Segurança', confidentiality: 'Interno', unitId: 'un-sgs', progress: 12,
        tags: ['segurança', 'câmeras'], createdAt: ts(-65), updatedAt: ts(-6),
      },
      {
        id: 'prj-6', orgId: ORG_PUB, code: 'PRJ-2024-018', name: 'Georreferenciamento Urbano',
        description: 'Base cartográfica georreferenciada e cadastro técnico multifinalitário.',
        objective: 'Base de dados espaciais única para todas as secretarias.',
        justification: 'Cadastros divergentes entre secretarias.',
        sponsorId: 'u-fernanda', managerId: 'u-carlos', teamIds: ['u-carlos', 'u-joao'],
        start: d(-400), plannedEnd: d(-40), actualEnd: d(-42), priority: 'Média', status: 'Concluído',
        objectiveIds: ['oe-3'], portfolioId: 'pf-1', budget: 1100000,
        methodology: 'Preditiva', type: 'Tecnologia', confidentiality: 'Interno', unitId: 'un-smi', progress: 100,
        tags: ['geoprocessamento'], createdAt: ts(-410), updatedAt: ts(-42),
      },
      {
        id: 'prj-7', orgId: ORG_PUB, code: 'PRJ-2025-006', name: 'Eficiência Energética em Prédios Públicos',
        description: 'Retrofit de iluminação, climatização e usinas solares em 8 prédios.',
        objective: 'Reduzir consumo energético em 28%.',
        justification: 'Conta de energia cresceu 41% em 24 meses.',
        sponsorId: 'u-fernanda', managerId: 'u-beatriz', teamIds: ['u-beatriz'],
        start: d(20), plannedEnd: d(320), priority: 'Média', status: 'Planejamento',
        objectiveIds: ['oe-2'], programId: 'pgm-2', portfolioId: 'pf-2', budget: 7300000,
        methodology: 'Preditiva', type: 'Infraestrutura', confidentiality: 'Público', unitId: 'un-sop', progress: 4,
        tags: ['energia', 'sustentabilidade'], createdAt: ts(-30), updatedAt: ts(-9),
      },
      {
        id: 'prj-s1', orgId: ORG_PRIV, code: 'PRJ-S-101', name: 'Plataforma BIM Integrada',
        description: 'Implantação de ambiente comum de dados (CDE) e modelagem BIM nível 2.',
        objective: 'Reduzir retrabalho de projeto em 35%.',
        justification: 'Retrabalho estimado em 12% do custo das obras.',
        sponsorId: 'u-sys2', managerId: 'u-sys1', teamIds: ['u-sys1'],
        start: d(-130), plannedEnd: d(110), priority: 'Alta', status: 'Em Execução',
        objectiveIds: ['oe-s1'], programId: 'pgm-s1', portfolioId: 'pf-sys', budget: 2400000,
        methodology: 'Híbrida', type: 'Tecnologia', confidentiality: 'Interno', unitId: 'un-ti', progress: 61,
        tags: ['bim', 'cde'], createdAt: ts(-135), updatedAt: ts(-3),
      },
      {
        id: 'prj-s2', orgId: ORG_PRIV, code: 'PRJ-S-102', name: 'Automação de Medições de Obra',
        description: 'Medições automáticas a partir de BIM com integração ao ERP.',
        objective: 'Reduzir ciclo de medição de 9 para 3 dias.',
        justification: 'Gargalo de medição atrasa pagamentos e fluxo de caixa.',
        sponsorId: 'u-sys2', managerId: 'u-sys1', teamIds: ['u-sys1'],
        start: d(-70), plannedEnd: d(150), priority: 'Alta', status: 'Em Execução',
        objectiveIds: ['oe-s1'], programId: 'pgm-s1', portfolioId: 'pf-sys', budget: 1600000,
        methodology: 'Ágil', type: 'Automação', confidentiality: 'Interno', unitId: 'un-ti', progress: 44,
        tags: ['automação', 'erp'], createdAt: ts(-75), updatedAt: ts(-2),
      },
      {
        id: 'prj-s3', orgId: ORG_PRIV, code: 'PRJ-S-103', name: 'Certificação ISO 37001 — Antissuborno',
        description: 'Implantação do sistema de gestão antissuborno e certificação.',
        objective: 'Certificação ISO 37001 até o fim do exercício.',
        justification: 'Exigência de clientes públicos e privados.',
        sponsorId: 'u-sys2', managerId: 'u-sys1', teamIds: ['u-sys1'],
        start: d(30), plannedEnd: d(280), priority: 'Média', status: 'Aprovado',
        objectiveIds: ['oe-s2'], portfolioId: 'pf-sys', budget: 850000,
        methodology: 'Preditiva', type: 'Compliance', confidentiality: 'Confidencial', unitId: 'un-dir', progress: 0,
        tags: ['compliance', 'iso'], createdAt: ts(-15), updatedAt: ts(-15),
      },
    ],
    tasks: [
      // Projeto 1 — Rede
      { id: 'tk-1', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '1.1', title: 'Levantamento do parque de switches', responsibleId: 'u-marcos', collaboratorIds: [], plannedStart: d(-150), plannedEnd: d(-130), actualStart: d(-150), actualEnd: d(-132), priority: 'Alta', status: 'Concluída', progress: 100, dependencies: [], estimatedH: 60, actualH: 54, tags: ['levantamento'], critical: false },
      { id: 'tk-2', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '1.2', title: 'Projeto executivo da nova topologia', responsibleId: 'u-carlos', collaboratorIds: ['u-marcos'], plannedStart: d(-132), plannedEnd: d(-100), actualStart: d(-132), actualEnd: d(-96), priority: 'Crítica', status: 'Concluída', progress: 100, dependencies: ['tk-1'], estimatedH: 120, actualH: 142, tags: ['projeto'], critical: true },
      { id: 'tk-3', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '2.1', title: 'Aquisição dos equipamentos de núcleo', responsibleId: 'u-joao', collaboratorIds: [], plannedStart: d(-95), plannedEnd: d(-40), actualStart: d(-95), priority: 'Crítica', status: 'Aguardando Terceiro', progress: 70, dependencies: ['tk-2'], estimatedH: 40, actualH: 30, tags: ['licitação'], critical: true, blockingReason: 'Fornecedor com atraso de entrega (nova previsão +18 dias).' },
      { id: 'tk-4', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '2.2', title: 'Migração dos prédios — Lote 1 (6 prédios)', responsibleId: 'u-marcos', collaboratorIds: ['u-carlos'], plannedStart: d(-35), plannedEnd: d(10), actualStart: d(-30), priority: 'Crítica', status: 'Em Andamento', progress: 62, dependencies: ['tk-3'], estimatedH: 200, actualH: 176, tags: ['migração'], critical: true },
      { id: 'tk-5', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '2.3', title: 'Migração dos prédios — Lote 2 (8 prédios)', responsibleId: 'u-marcos', collaboratorIds: [], plannedStart: d(12), plannedEnd: d(40), priority: 'Alta', status: 'Planejada', progress: 0, dependencies: ['tk-4'], estimatedH: 260, actualH: 0, tags: ['migração'], critical: true },
      { id: 'tk-6', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '3.1', title: 'Monitoramento e documentação as-built', responsibleId: 'u-carlos', collaboratorIds: [], plannedStart: d(30), plannedEnd: d(45), priority: 'Média', status: 'Não Iniciada', progress: 0, dependencies: ['tk-5'], estimatedH: 80, actualH: 0, tags: ['documentação'], critical: false },
      // Projeto 2 — Portal (Ágil)
      { id: 'tk-7', orgId: ORG_PUB, projectId: 'prj-2', wbsCode: 'S3', title: 'Sprint 3 — Agendamento de serviços', responsibleId: 'u-carlos', collaboratorIds: ['u-joao'], plannedStart: d(-21), plannedEnd: d(-7), actualStart: d(-21), actualEnd: d(-7), priority: 'Alta', status: 'Concluída', progress: 100, dependencies: [], estimatedH: 110, actualH: 104, tags: ['sprint', 'agendamento'], critical: false },
      { id: 'tk-8', orgId: ORG_PUB, projectId: 'prj-2', wbsCode: 'S4', title: 'Sprint 4 — Protocolo digital e notificações', responsibleId: 'u-joao', collaboratorIds: ['u-carlos'], plannedStart: d(-7), plannedEnd: d(7), actualStart: d(-7), priority: 'Alta', status: 'Em Andamento', progress: 74, dependencies: ['tk-7'], estimatedH: 120, actualH: 92, tags: ['sprint', 'protocolo'], critical: true },
      { id: 'tk-9', orgId: ORG_PUB, projectId: 'prj-2', wbsCode: 'S4', title: 'Integração com base de contribuintes', responsibleId: 'u-joao', collaboratorIds: [], plannedStart: d(-5), plannedEnd: d(2), actualStart: d(-5), priority: 'Crítica', status: 'Bloqueada', progress: 35, dependencies: ['tk-7'], estimatedH: 60, actualH: 38, tags: ['integração'], critical: true, blockingReason: 'Aguardando credenciais do webservice da Fazenda.' },
      { id: 'tk-10', orgId: ORG_PUB, projectId: 'prj-2', wbsCode: 'S5', title: 'Sprint 5 — Portal de transparência de serviços', responsibleId: 'u-carlos', collaboratorIds: [], plannedStart: d(8), plannedEnd: d(22), priority: 'Média', status: 'Planejada', progress: 0, dependencies: ['tk-8'], estimatedH: 120, actualH: 0, tags: ['sprint'], critical: false },
      // Projeto 3 — Av. Central (Preditiva, atrasado)
      { id: 'tk-11', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '1', title: 'Drenagem — trecho norte', responsibleId: 'u-beatriz', collaboratorIds: ['u-marcos'], plannedStart: d(-240), plannedEnd: d(-140), actualStart: d(-240), actualEnd: d(-122), priority: 'Crítica', status: 'Concluída', progress: 100, dependencies: [], estimatedH: 900, actualH: 1010, tags: ['drenagem'], critical: true },
      { id: 'tk-12', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '2', title: 'Recapeamento asfáltico 4,2 km', responsibleId: 'u-beatriz', collaboratorIds: [], plannedStart: d(-140), plannedEnd: d(-20), actualStart: d(-122), priority: 'Crítica', status: 'Em Andamento', progress: 81, dependencies: ['tk-11'], estimatedH: 1400, actualH: 1240, tags: ['pavimento'], critical: true },
      { id: 'tk-13', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '3', title: 'Calçadas acessíveis e sinalização', responsibleId: 'u-marcos', collaboratorIds: [], plannedStart: d(-60), plannedEnd: d(10), actualStart: d(-52), priority: 'Alta', status: 'Em Andamento', progress: 48, dependencies: ['tk-11'], estimatedH: 500, actualH: 310, tags: ['calçadas'], critical: true },
      { id: 'tk-14', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '4', title: 'Ciclovia e paisagismo', responsibleId: 'u-beatriz', collaboratorIds: [], plannedStart: d(-30), plannedEnd: d(25), actualStart: d(-18), priority: 'Alta', status: 'Em Andamento', progress: 22, dependencies: ['tk-12'], estimatedH: 620, actualH: 210, tags: ['ciclovia'], critical: true },
      { id: 'tk-15', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '5', title: 'Medição final e entrega à fiscalização', responsibleId: 'u-beatriz', collaboratorIds: [], plannedStart: d(22), plannedEnd: d(30), priority: 'Crítica', status: 'Não Iniciada', progress: 0, dependencies: ['tk-13', 'tk-14'], estimatedH: 60, actualH: 0, tags: ['entrega'], critical: true },
      // Projeto 4 — Processo eletrônico
      { id: 'tk-16', orgId: ORG_PUB, projectId: 'prj-4', wbsCode: '1.1', title: 'Mapeamento dos 40 fluxos prioritários', responsibleId: 'u-joao', collaboratorIds: ['u-ana'], plannedStart: d(-80), plannedEnd: d(-45), actualStart: d(-80), actualEnd: d(-40), priority: 'Alta', status: 'Concluída', progress: 100, dependencies: [], estimatedH: 160, actualH: 175, tags: ['processos'], critical: false },
      { id: 'tk-17', orgId: ORG_PUB, projectId: 'prj-4', wbsCode: '2.1', title: 'Configuração da plataforma de tramitação', responsibleId: 'u-carlos', collaboratorIds: ['u-joao'], plannedStart: d(-45), plannedEnd: d(0), actualStart: d(-40), priority: 'Alta', status: 'Em Andamento', progress: 78, dependencies: ['tk-16'], estimatedH: 200, actualH: 160, tags: ['plataforma'], critical: true },
      { id: 'tk-18', orgId: ORG_PUB, projectId: 'prj-4', wbsCode: '2.2', title: 'Assinatura eletrônica — integração ICP-Brasil', responsibleId: 'u-carlos', collaboratorIds: [], plannedStart: d(-20), plannedEnd: d(15), actualStart: d(-12), priority: 'Crítica', status: 'Em Revisão', progress: 85, dependencies: ['tk-17'], estimatedH: 90, actualH: 80, tags: ['assinatura'], critical: false },
      { id: 'tk-19', orgId: ORG_PUB, projectId: 'prj-4', wbsCode: '3.1', title: 'Piloto na Secretaria da Fazenda', responsibleId: 'u-ana', collaboratorIds: ['u-paulo'], plannedStart: d(5), plannedEnd: d(40), priority: 'Média', status: 'Planejada', progress: 0, dependencies: ['tk-18'], estimatedH: 120, actualH: 0, tags: ['piloto'], critical: false },
      // Projeto 5 — Videomonitoramento
      { id: 'tk-20', orgId: ORG_PUB, projectId: 'prj-5', wbsCode: '1', title: 'Estudo de cobertura e pontos de câmera', responsibleId: 'u-beatriz', collaboratorIds: [], plannedStart: d(-60), plannedEnd: d(-25), actualStart: d(-60), actualEnd: d(-22), priority: 'Alta', status: 'Concluída', progress: 100, dependencies: [], estimatedH: 140, actualH: 150, tags: ['estudo'], critical: false },
      { id: 'tk-21', orgId: ORG_PUB, projectId: 'prj-5', wbsCode: '2', title: 'Termo de referência e licitação', responsibleId: 'u-joao', collaboratorIds: ['u-beatriz'], plannedStart: d(-20), plannedEnd: d(30), actualStart: d(-15), priority: 'Crítica', status: 'Em Andamento', progress: 30, dependencies: ['tk-20'], estimatedH: 100, actualH: 40, tags: ['licitação'], critical: true },
      // Systenex
      { id: 'tk-s1', orgId: ORG_PRIV, projectId: 'prj-s1', wbsCode: '2.1', title: 'CDE — migração dos modelos ativos', responsibleId: 'u-sys1', collaboratorIds: [], plannedStart: d(-40), plannedEnd: d(5), actualStart: d(-38), priority: 'Alta', status: 'Em Andamento', progress: 72, dependencies: [], estimatedH: 150, actualH: 118, tags: ['cde'], critical: true },
      { id: 'tk-s2', orgId: ORG_PRIV, projectId: 'prj-s2', wbsCode: '1.2', title: 'Conectores ERP × BIM (medição)', responsibleId: 'u-sys1', collaboratorIds: [], plannedStart: d(-30), plannedEnd: d(10), actualStart: d(-28), priority: 'Crítica', status: 'Em Andamento', progress: 55, dependencies: [], estimatedH: 180, actualH: 121, tags: ['integração'], critical: true },
      { id: 'tk-s3', orgId: ORG_PRIV, projectId: 'prj-s2', wbsCode: '2.1', title: 'Homologação com obra piloto', responsibleId: 'u-sys1', collaboratorIds: [], plannedStart: d(12), plannedEnd: d(45), priority: 'Alta', status: 'Planejada', progress: 0, dependencies: ['tk-s2'], estimatedH: 120, actualH: 0, tags: ['homologação'], critical: false },
      // Tarefas genéricas vencidas para alimentar alertas
      { id: 'tk-22', orgId: ORG_PUB, projectId: 'prj-1', wbsCode: '2.4', title: 'Validar redundância de energia do datacenter', responsibleId: 'u-marcos', collaboratorIds: [], plannedStart: d(-18), plannedEnd: d(-6), actualStart: d(-18), priority: 'Alta', status: 'Em Andamento', progress: 40, dependencies: [], estimatedH: 30, actualH: 22, tags: ['datacenter'], critical: true },
      { id: 'tk-23', orgId: ORG_PUB, projectId: 'prj-3', wbsCode: '3.2', title: 'Remanejar posteamento — concessionária', responsibleId: 'u-beatriz', collaboratorIds: [], plannedStart: d(-25), plannedEnd: d(-3), priority: 'Crítica', status: 'Aguardando Terceiro', progress: 20, dependencies: [], estimatedH: 40, actualH: 12, tags: ['concessionária'], critical: true, blockingReason: 'Concessionária não confirmou janela de desligamento.' },
      { id: 'tk-24', orgId: ORG_PUB, projectId: 'prj-2', wbsCode: 'S4', title: 'Testes de acessibilidade WCAG 2.1', responsibleId: 'u-joao', collaboratorIds: [], plannedStart: d(-10), plannedEnd: d(-2), priority: 'Média', status: 'Em Revisão', progress: 90, dependencies: ['tk-8'], estimatedH: 40, actualH: 36, tags: ['qualidade'], critical: false },
    ],
    milestones: [
      { id: 'ms-1', projectId: 'prj-1', name: 'Núcleo de rede em produção', planned: d(-40), forecast: d(-22), status: 'Atrasado', responsibleId: 'u-carlos' },
      { id: 'ms-2', projectId: 'prj-1', name: 'Lote 1 migrado (6 prédios)', planned: d(10), forecast: d(10), status: 'Em risco', responsibleId: 'u-marcos' },
      { id: 'ms-3', projectId: 'prj-1', name: 'Encerramento do projeto', planned: d(45), forecast: d(63), status: 'Em risco', responsibleId: 'u-carlos' },
      { id: 'ms-4', projectId: 'prj-3', name: 'Recapeamento 100%', planned: d(-20), forecast: d(-2), status: 'Atrasado', responsibleId: 'u-beatriz' },
      { id: 'ms-5', projectId: 'prj-3', name: 'Entrega ao fiscal do contrato', planned: d(30), forecast: d(48), status: 'Em risco', responsibleId: 'u-beatriz' },
      { id: 'ms-6', projectId: 'prj-2', name: 'Go-live do protocolo digital', planned: d(22), forecast: d(22), status: 'No prazo', responsibleId: 'u-carlos' },
      { id: 'ms-7', projectId: 'prj-4', name: 'Piloto Fazenda em produção', planned: d(40), forecast: d(40), status: 'No prazo', responsibleId: 'u-ana' },
      { id: 'ms-8', projectId: 'prj-6', name: 'Assinatura dos contratos de retrofit', planned: d(-42), actual: d(-42), status: 'Concluído', responsibleId: 'u-carlos' },
    ],
    risks: [
      { id: 'rk-1', orgId: ORG_PUB, projectId: 'prj-1', code: 'RSK-001', title: 'Atraso na entrega dos equipamentos de núcleo', description: 'Fornecedor informou novo prazo 18 dias após o contratado.', category: 'Fornecedor', probability: 5, impact: 5, ownerId: 'u-carlos', trigger: 'Comunicação formal do fornecedor', response: 'Mitigar', mitigation: 'Cobrança semanal, multa contratual e plano de migração parcial.', contingency: 'Utilizar switches atuais em configuração provisória.', status: 'Materializado', reviewAt: d(7) },
      { id: 'rk-2', orgId: ORG_PUB, projectId: 'prj-1', code: 'RSK-002', title: 'Indisponibilidade de serviços durante janelas de migração', description: 'Migração fora da janela pode afetar saúde e fazenda.', category: 'Técnico', probability: 3, impact: 4, ownerId: 'u-marcos', response: 'Mitigar', mitigation: 'Janelas noturnas e rollback documentado.', status: 'Monitorando', reviewAt: d(10) },
      { id: 'rk-3', orgId: ORG_PUB, projectId: 'prj-3', code: 'RSK-003', title: 'Chuva acima da média no período de pavimentação', description: 'Período chuvoso pode reduzir ritmo de pavimentação em até 40%.', category: 'Ambiental', probability: 4, impact: 4, ownerId: 'u-beatriz', response: 'Mitigar', mitigation: 'Frentes cobertas e replanejamento semanal.', status: 'Monitorando', reviewAt: d(5) },
      { id: 'rk-4', orgId: ORG_PUB, projectId: 'prj-3', code: 'RSK-004', title: 'Remanejamento de posteamento sem janela confirmada', description: 'Dependência da concessionária sem data confirmada.', category: 'Externo', probability: 4, impact: 5, ownerId: 'u-beatriz', response: 'Mitigar', mitigation: 'Escalonamento à agência reguladora.', contingency: 'Executar trechos independentes primeiro.', status: 'Monitorando', reviewAt: d(3) },
      { id: 'rk-5', orgId: ORG_PUB, projectId: 'prj-2', code: 'RSK-005', title: 'Integração com Fazenda sem credenciais liberadas', description: 'Bloqueio atual da sprint 4.', category: 'Integração', probability: 4, impact: 3, ownerId: 'u-carlos', response: 'Mitigar', mitigation: 'Reunião com TI da Fazenda agendada.', status: 'Monitorando', reviewAt: d(4) },
      { id: 'rk-6', orgId: ORG_PUB, projectId: 'prj-5', code: 'RSK-006', title: 'Licitação deserta em lotes de analíticos de vídeo', description: 'Mercado concentrado pode frustrar o certame.', category: 'Aquisições', probability: 2, impact: 4, ownerId: 'u-joao', response: 'Mitigar', mitigation: 'Pesquisa de mercado ampliada e lotes separados.', status: 'Identificado', reviewAt: d(20) },
      { id: 'rk-7', orgId: ORG_PUB, code: 'RSK-PRT-01', title: 'Sobrecarga da equipe de infraestrutura (Marcos 126%)', description: 'Alocação acima da capacidade sustentável por 6 semanas consecutivas.', category: 'Recursos', probability: 5, impact: 3, ownerId: 'u-mariana', response: 'Mitigar', mitigation: 'Redistribuição de tarefas não críticas.', status: 'Monitorando', reviewAt: d(6), aiSuggested: true },
      { id: 'rk-8', orgId: ORG_PUB, code: 'RSK-PRT-02', title: '12 demandas correlatas de rede sem consolidação', description: 'Padrão detectado: demandas de modernização de rede tratadas isoladamente.', category: 'Portfólio', probability: 4, impact: 4, ownerId: 'u-ricardo', response: 'Mitigar', mitigation: 'Avaliar consolidação em programa de conectividade.', status: 'Sugestão da IA', reviewAt: d(15), aiSuggested: true },
      { id: 'rk-s1', orgId: ORG_PRIV, projectId: 'prj-s2', code: 'RSK-S-01', title: 'Instabilidade da API do ERP na homologação', description: 'API do ERP com timeouts em ambiente de homologação.', category: 'Técnico', probability: 3, impact: 4, ownerId: 'u-sys1', response: 'Mitigar', mitigation: 'Retry com fila e monitoramento.', status: 'Monitorando', reviewAt: d(8) },
    ],
    issues: [
      { id: 'is-1', orgId: ORG_PUB, projectId: 'prj-1', title: 'Equipamentos de núcleo fora do prazo contratual', impact: 'Marco "Núcleo em produção" atrasado 18 dias', severity: 'Crítica', responsibleId: 'u-carlos', rootCause: 'Ruptura de componentes do fornecedor', correctiveAction: 'Notificação contratual + cronograma de entrega parcial', deadline: d(12), status: 'Em Tratamento', createdAt: ts(-9) },
      { id: 'is-2', orgId: ORG_PUB, projectId: 'prj-3', title: 'Interferência de posteamento no trecho 3', impact: 'Frente de calçadas parada no trecho 3', severity: 'Alta', responsibleId: 'u-beatriz', rootCause: 'Cadastro da concessionária desatualizado', correctiveAction: 'Escalonamento formal à agência reguladora', deadline: d(9), status: 'Em Tratamento', createdAt: ts(-14) },
      { id: 'is-3', orgId: ORG_PUB, projectId: 'prj-2', title: 'Credenciais do webservice da Fazenda não liberadas', impact: 'Sprint 4 com integração bloqueada', severity: 'Alta', responsibleId: 'u-joao', correctiveAction: 'Reunião com TI da Fazenda', deadline: d(5), status: 'Em Tratamento', createdAt: ts(-6) },
      { id: 'is-4', orgId: ORG_PUB, projectId: 'prj-3', title: 'Solo com capacidade abaixo do previsto no trecho 2', impact: 'Reforço de base adicionou R$ 210 mil', severity: 'Média', responsibleId: 'u-beatriz', rootCause: 'Sondagem insuficiente na fase de projeto', correctiveAction: 'Complementação de sondagem em projetos futuros', status: 'Resolvido', createdAt: ts(-60) },
    ],
    changes: [
      { id: 'ch-1', orgId: ORG_PUB, projectId: 'prj-3', code: 'MUD-2025-011', title: 'Reforço de base no trecho 2 (solo)', reason: 'Capacidade de suporte abaixo do especificado.', requesterId: 'u-beatriz', scopeImpact: 'Baixo', costImpact: 210000, scheduleImpactDays: 6, riskImpact: 'Reduz risco de recalque', recommendation: 'Aprovar — segurança estrutural', status: 'Aprovada', createdAt: ts(-55), decidedAt: d(-50) },
      { id: 'ch-2', orgId: ORG_PUB, projectId: 'prj-1', code: 'MUD-2025-014', title: 'Prorrogar marco de núcleo em 18 dias', reason: 'Atraso confirmado do fornecedor.', requesterId: 'u-carlos', scopeImpact: 'Nenhum', costImpact: 0, scheduleImpactDays: 18, riskImpact: 'Mantém exposição a indisponibilidade', recommendation: 'Aprovar com plano de contingência', status: 'Em Análise', createdAt: ts(-7) },
      { id: 'ch-3', orgId: ORG_PUB, projectId: 'prj-2', code: 'MUD-2025-015', title: 'Incluir módulo de ouvidoria na sprint 6', reason: 'Demanda do gabinete.', requesterId: 'u-ana', scopeImpact: 'Médio', costImpact: 120000, scheduleImpactDays: 10, riskImpact: 'Posterga transparência de serviços', status: 'Solicitada', createdAt: ts(-2) },
      { id: 'ch-4', orgId: ORG_PUB, projectId: 'prj-5', code: 'MUD-2025-016', title: 'Substituir tecnologia de analíticos por API aberta', reason: 'Redução de custo e dependência de fornecedor.', requesterId: 'u-beatriz', scopeImpact: 'Alto', costImpact: -430000, scheduleImpactDays: 15, riskImpact: 'Novo risco técnico a avaliar', status: 'Solicitada', createdAt: ts(-1) },
    ],
    costs: [
      { id: 'ct-1', orgId: ORG_PUB, projectId: 'prj-1', month: m(-4), category: 'Equipamentos', planned: 480000, actual: 460000, committed: 1900000, publicTerms: { dotacao: 4200000, empenho: 2380000, liquidacao: 460000, contract: 'CT-2025-031' } },
      { id: 'ct-2', orgId: ORG_PUB, projectId: 'prj-1', month: m(-3), category: 'Equipamentos', planned: 520000, actual: 545000, committed: 1380000, publicTerms: { empenho: 2380000, liquidacao: 545000 } },
      { id: 'ct-3', orgId: ORG_PUB, projectId: 'prj-1', month: m(-2), category: 'Serviços', planned: 310000, actual: 342000, committed: 900000, publicTerms: { liquidacao: 342000 } },
      { id: 'ct-4', orgId: ORG_PUB, projectId: 'prj-1', month: m(-1), category: 'Serviços', planned: 330000, actual: 391000, committed: 560000, publicTerms: { liquidacao: 391000 } },
      { id: 'ct-5', orgId: ORG_PUB, projectId: 'prj-1', month: m(0), category: 'Serviços', planned: 350000, actual: 118000, committed: 420000, publicTerms: { liquidacao: 118000 } },
      { id: 'ct-6', orgId: ORG_PUB, projectId: 'prj-3', month: m(-3), category: 'Obras', planned: 1400000, actual: 1380000, committed: 8400000, publicTerms: { dotacao: 12600000, empenho: 9800000, liquidacao: 1380000, contract: 'CT-2024-112' } },
      { id: 'ct-7', orgId: ORG_PUB, projectId: 'prj-3', month: m(-2), category: 'Obras', planned: 1500000, actual: 1730000, committed: 6100000, publicTerms: { liquidacao: 1730000 } },
      { id: 'ct-8', orgId: ORG_PUB, projectId: 'prj-3', month: m(-1), category: 'Obras', planned: 1450000, actual: 1610000, committed: 4300000, publicTerms: { liquidacao: 1610000 } },
      { id: 'ct-9', orgId: ORG_PUB, projectId: 'prj-3', month: m(0), category: 'Obras', planned: 1400000, actual: 620000, committed: 3700000, publicTerms: { liquidacao: 620000 } },
      { id: 'ct-10', orgId: ORG_PUB, projectId: 'prj-2', month: m(-2), category: 'Desenvolvimento', planned: 260000, actual: 248000, committed: 1400000, publicTerms: { dotacao: 2800000, empenho: 1960000, liquidacao: 248000 } },
      { id: 'ct-11', orgId: ORG_PUB, projectId: 'prj-2', month: m(-1), category: 'Desenvolvimento', planned: 280000, actual: 271000, committed: 1150000, publicTerms: { liquidacao: 271000 } },
      { id: 'ct-12', orgId: ORG_PUB, projectId: 'prj-2', month: m(0), category: 'Desenvolvimento', planned: 280000, actual: 95000, committed: 1050000, publicTerms: { liquidacao: 95000 } },
      { id: 'ct-13', orgId: ORG_PUB, projectId: 'prj-4', month: m(-1), category: 'Licenças', planned: 190000, actual: 186000, committed: 950000, publicTerms: { dotacao: 1900000, empenho: 1100000, liquidacao: 186000 } },
      { id: 'ct-14', orgId: ORG_PUB, projectId: 'prj-4', month: m(0), category: 'Licenças', planned: 200000, actual: 62000, committed: 760000, publicTerms: { liquidacao: 62000 } },
      { id: 'ct-s1', orgId: ORG_PRIV, projectId: 'prj-s1', month: m(-2), category: 'Software', planned: 220000, actual: 214000, committed: 1200000 },
      { id: 'ct-s2', orgId: ORG_PRIV, projectId: 'prj-s1', month: m(-1), category: 'Software', planned: 230000, actual: 226000, committed: 980000 },
      { id: 'ct-s3', orgId: ORG_PRIV, projectId: 'prj-s2', month: m(-1), category: 'Desenvolvimento', planned: 180000, actual: 196000, committed: 820000 },
      { id: 'ct-s4', orgId: ORG_PRIV, projectId: 'prj-s2', month: m(0), category: 'Desenvolvimento', planned: 190000, actual: 74000, committed: 640000 },
    ],
    teams: [
      { id: 'tm-1', orgId: ORG_PUB, name: 'Equipe de Infraestrutura de TI', leadId: 'u-carlos', memberIds: ['u-carlos', 'u-marcos', 'u-joao'] },
      { id: 'tm-2', orgId: ORG_PUB, name: 'Equipe de Obras Viárias', leadId: 'u-beatriz', memberIds: ['u-beatriz', 'u-marcos'] },
      { id: 'tm-3', orgId: ORG_PUB, name: 'PMO Central', leadId: 'u-mariana', memberIds: ['u-mariana', 'u-joao'] },
      { id: 'tm-s1', orgId: ORG_PRIV, name: 'Squad Digital Systenex', leadId: 'u-sys1', memberIds: ['u-sys1'] },
    ],
    allocations: [
      { id: 'al-1', userId: 'u-carlos', projectId: 'prj-1', percent: 50, role: 'Gerente de Projeto', from: d(-150), to: d(45) },
      { id: 'al-2', userId: 'u-carlos', projectId: 'prj-2', percent: 40, role: 'Gerente de Projeto', from: d(-110), to: d(90) },
      { id: 'al-3', userId: 'u-carlos', projectId: 'prj-4', percent: 30, role: 'Gerente de Projeto', from: d(-80), to: d(140) },
      { id: 'al-4', userId: 'u-marcos', projectId: 'prj-1', percent: 80, role: 'Técnico de Infraestrutura', from: d(-150), to: d(45) },
      { id: 'al-5', userId: 'u-marcos', projectId: 'prj-3', percent: 35, role: 'Apoio de campo', from: d(-240), to: d(30) },
      { id: 'al-6', userId: 'u-joao', projectId: 'prj-1', percent: 30, role: 'Analista', from: d(-150), to: d(45) },
      { id: 'al-7', userId: 'u-joao', projectId: 'prj-2', percent: 45, role: 'Desenvolvimento', from: d(-110), to: d(90) },
      { id: 'al-8', userId: 'u-joao', projectId: 'prj-4', percent: 25, role: 'Analista de processos', from: d(-80), to: d(140) },
      { id: 'al-9', userId: 'u-beatriz', projectId: 'prj-3', percent: 70, role: 'Gerente de Projeto', from: d(-240), to: d(30) },
      { id: 'al-10', userId: 'u-beatriz', projectId: 'prj-5', percent: 25, role: 'Gerente de Projeto', from: d(-60), to: d(180) },
      { id: 'al-s1', userId: 'u-sys1', projectId: 'prj-s1', percent: 55, role: 'Gerente de Projeto', from: d(-130), to: d(110) },
      { id: 'al-s2', userId: 'u-sys1', projectId: 'prj-s2', percent: 45, role: 'Gerente de Projeto', from: d(-70), to: d(150) },
    ],
    raci: [
      { id: 'rc-1', projectId: 'prj-1', activity: 'Migração de prédios (lotes)', raci: { 'u-marcos': 'R', 'u-carlos': 'A', 'u-mariana': 'C', 'u-fernanda': 'I' } },
      { id: 'rc-2', projectId: 'prj-1', activity: 'Aceite dos equipamentos de núcleo', raci: { 'u-carlos': 'R', 'u-fernanda': 'A', 'u-paulo': 'C', 'u-mariana': 'I' } },
      { id: 'rc-3', projectId: 'prj-3', activity: 'Medições mensais da obra', raci: { 'u-beatriz': 'R', 'u-fernanda': 'A', 'u-paulo': 'C', 'u-mariana': 'I' } },
      { id: 'rc-4', projectId: 'prj-2', activity: 'Priorização do backlog', raci: { 'u-carlos': 'A', 'u-joao': 'R', 'u-ana': 'C', 'u-fernanda': 'I' } },
    ],
    stakeholders: [
      { id: 'sh-1', projectId: 'prj-1', name: 'Fernanda Alves', organization: 'Secretaria de Modernização', role: 'Sponsor', influence: 5, interest: 4, impact: 'Aprova mudanças de linha de base', engagement: 'Líder', strategy: 'Relatório executivo quinzenal' },
      { id: 'sh-2', projectId: 'prj-1', name: 'TI da Fazenda', organization: 'Secretaria da Fazenda', role: 'Fornecedor de integração', influence: 3, interest: 2, impact: 'Libera credenciais de sistemas', engagement: 'Neutro', strategy: 'Reuniões técnicas semanais' },
      { id: 'sh-3', projectId: 'prj-3', name: 'Concessionária de Energia', organization: 'Concessionária', role: 'Dependência externa', influence: 4, interest: 1, impact: 'Remanejamento de posteamento', engagement: 'Resistente', strategy: 'Escalonamento regulatório + ofícios formais' },
      { id: 'sh-4', projectId: 'prj-2', name: 'População', organization: 'Município', role: 'Usuária final', influence: 2, interest: 5, impact: 'Adoção dos serviços digitais', engagement: 'Apoiador', strategy: 'Comunicação em canais oficiais' },
    ],
    meetings: [
      { id: 'mt-1', orgId: ORG_PUB, projectId: 'prj-1', title: 'Comitê de crise — núcleo de rede', date: ts(-3, 14), participantIds: ['u-fernanda', 'u-carlos', 'u-mariana', 'u-marcos'], agenda: '1) Status do fornecedor; 2) Plano de contingência; 3) Comunicação às secretarias.', minutes: 'Fornecedor confirmou entrega parcial em 12 dias. Definido plano de migração provisória com switches atuais. Comunicação oficial às secretarias será enviada pelo PMO.', decisions: ['Aprovar migração provisória do lote 1', 'Aplicar multa contratual após parecer jurídico'], actions: ['Marcos: validar energia do datacenter até sexta', 'Mariana: comunicar secretarias', 'Carlos: revisar cronograma com novo prazo'], status: 'Realizada' },
      { id: 'mt-2', orgId: ORG_PUB, title: 'Revisão mensal do portfólio', date: ts(2, 9), participantIds: ['u-fernanda', 'u-ricardo', 'u-mariana', 'u-carlos', 'u-beatriz'], agenda: 'Saúde do portfólio, priorização de demandas e decisões pendentes.', status: 'Agendada' },
      { id: 'mt-3', orgId: ORG_PUB, projectId: 'prj-2', title: 'Sprint Review — Sprint 4', date: ts(-1, 15), participantIds: ['u-carlos', 'u-joao', 'u-ana'], agenda: 'Demonstração do protocolo digital e testes de acessibilidade.', minutes: 'Protocolo digital aprovado pelos usuários-piloto. Acessibilidade com 2 apontamentos leves.', decisions: ['Manter go-live do protocolo para a sprint 5'], actions: ['João: corrigir apontamentos de acessibilidade'], status: 'Realizada' },
    ],
    decisions: [
      { id: 'dc-1', orgId: ORG_PUB, projectId: 'prj-1', title: 'Migração provisória com switches atuais', date: d(-3), decisionMakerId: 'u-fernanda', context: 'Atraso de 18 dias do fornecedor comprometeria o lote 1.', alternatives: ['Aguardar entrega total', 'Migração parcial provisória', 'Rescindir contrato'], selected: 'Migração parcial provisória', reason: 'Mantém cronograma do lote 1 com risco controlado e rollback documentado.', impact: 'Risco técnico temporário adicional', status: 'Aprovada' },
      { id: 'dc-2', orgId: ORG_PUB, projectId: 'prj-3', title: 'Reforço de base no trecho 2', date: d(-50), decisionMakerId: 'u-fernanda', context: 'Solo com capacidade abaixo do especificado.', alternatives: ['Executar conforme projeto', 'Reforço de base', 'Redesenho do trecho'], selected: 'Reforço de base', reason: 'Solução tecnicamente recomendada com menor impacto de prazo.', impact: '+R$ 210 mil e +6 dias', status: 'Registrada' },
      { id: 'dc-3', orgId: ORG_PUB, title: 'Consolidar demandas de rede em programa', date: d(0), decisionMakerId: 'u-fernanda', context: '12 demandas correlatas de modernização de rede identificadas pela IA.', alternatives: ['Tratar isoladamente', 'Consolidar em programa de conectividade'], selected: '', reason: '', impact: 'Visão unificada de investimento e capacidade', status: 'Pendente' },
      { id: 'dc-4', orgId: ORG_PUB, projectId: 'prj-5', title: 'Adotar API aberta de analíticos de vídeo', date: d(0), decisionMakerId: 'u-fernanda', context: 'MUD-2025-016 propõe substituição de tecnologia.', alternatives: ['Manter tecnologia proprietária', 'API aberta'], selected: '', reason: '', impact: 'Economia estimada de R$ 430 mil', status: 'Pendente' },
    ],
    documents: [
      { id: 'doc-1', orgId: ORG_PUB, projectId: 'prj-1', name: 'Termo de Abertura — Rede 2025.pdf', category: 'Termo de Abertura', folder: 'Governança', tags: ['tap', 'assinado'], version: 2, uploadedAt: ts(-150), responsibleId: 'u-mariana', confidentiality: 'Interno', sizeKb: 840 },
      { id: 'doc-2', orgId: ORG_PUB, projectId: 'prj-1', name: 'Projeto executivo de topologia v3.pdf', category: 'Projeto Técnico', folder: 'Engenharia', tags: ['rede', 'topologia'], version: 3, uploadedAt: ts(-96), responsibleId: 'u-carlos', confidentiality: 'Interno', sizeKb: 2650 },
      { id: 'doc-3', orgId: ORG_PUB, projectId: 'prj-3', name: 'Medição 08 — Av. Central.xlsx', category: 'Medição', folder: 'Contratos', tags: ['medição', 'fiscal'], version: 1, uploadedAt: ts(-8), responsibleId: 'u-beatriz', confidentiality: 'Interno', sizeKb: 310 },
      { id: 'doc-4', orgId: ORG_PUB, projectId: 'prj-3', name: 'Contrato CT-2024-112 (consolidado).pdf', category: 'Contrato', folder: 'Contratos', tags: ['contrato'], version: 4, uploadedAt: ts(-200), responsibleId: 'u-paulo', confidentiality: 'Confidencial', sizeKb: 1520 },
      { id: 'doc-5', orgId: ORG_PUB, projectId: 'prj-2', name: 'Relatório de testes de acessibilidade.pdf', category: 'Evidência', folder: 'Qualidade', tags: ['wcag'], version: 1, uploadedAt: ts(-2), responsibleId: 'u-joao', confidentiality: 'Público', sizeKb: 620 },
      { id: 'doc-6', orgId: ORG_PUB, name: 'Ata — Comitê de crise rede.docx', category: 'Ata', folder: 'Reuniões', tags: ['ata'], version: 1, uploadedAt: ts(-3), responsibleId: 'u-mariana', confidentiality: 'Interno', sizeKb: 95 },
      { id: 'doc-s1', orgId: ORG_PRIV, projectId: 'prj-s1', name: 'Plano de adoção BIM nível 2.pdf', category: 'Plano do Projeto', folder: 'Planejamento', tags: ['bim'], version: 1, uploadedAt: ts(-100), responsibleId: 'u-sys1', confidentiality: 'Interno', sizeKb: 1130 },
    ],
    benefits: [
      { id: 'bf-1', projectId: 'prj-1', description: 'Disponibilidade da rede municipal', type: 'Operacional', baseline: '97,2%', target: '99,9%', method: 'Monitoramento contínuo (Zabbix)', responsibleId: 'u-marcos', measureAt: d(90) },
      { id: 'bf-2', projectId: 'prj-2', description: 'Serviços públicos digitais', type: 'Estratégico', baseline: '42%', target: '70%', method: 'Inventário de serviços do portal', responsibleId: 'u-carlos', measureAt: d(120) },
      { id: 'bf-3', projectId: 'prj-3', description: 'Tempo médio de travessia da Av. Central', type: 'Social', baseline: '19 min', target: '12 min', method: 'Contagem em horário de pico', responsibleId: 'u-beatriz', measureAt: d(150) },
      { id: 'bf-4', projectId: 'prj-6', description: 'Consumo energético dos prédios públicos', type: 'Financeiro', baseline: '1,9 GWh/ano', target: '1,37 GWh/ano', method: 'Faturas de energia', responsibleId: 'u-beatriz', measureAt: d(360), actual: undefined },
    ],
    lessons: [
      { id: 'ls-1', orgId: ORG_PUB, projectId: 'prj-6', situation: 'Assinatura dos contratos de retrofit', happened: 'Contratos assinados 12 dias antes do previsto', cause: 'Termo de referência padronizado e parecer jurídico antecipado', lesson: 'Padronização de TR acelera aquisições em até 30%', recommendation: 'Adotar banco de TRs por categoria de contratação', category: 'Aquisições', createdAt: ts(-40) },
      { id: 'ls-2', orgId: ORG_PUB, projectId: 'prj-3', situation: 'Execução do trecho 2', happened: 'Solo com capacidade abaixo do previsto', cause: 'Sondagem com espaçamento maior que o recomendado', lesson: 'Sondagem insuficiente gera mudanças caras em obra', recommendation: 'Espaçamento máximo de 50 m em vias urbanas', category: 'Engenharia', createdAt: ts(-55) },
      { id: 'ls-3', orgId: ORG_PUB, projectId: 'prj-6', situation: 'Georreferenciamento urbano', happened: 'Entrega dentro do prazo com qualidade superior', cause: 'Revisões quinzenais com as secretarias usuárias', lesson: 'Validação frequente evita retrabalho de base de dados', recommendation: 'Ciclos de validação curtos em projetos de dados', category: 'Qualidade', createdAt: ts(-42) },
    ],
    health: [
      { id: 'hs-1', projectId: 'prj-1', at: d(-30), overall: 71, dims: [ { label: 'Cronograma', value: 74 }, { label: 'Custos', value: 88 }, { label: 'Escopo', value: 86 }, { label: 'Riscos', value: 62 }, { label: 'Equipe', value: 70 }, { label: 'Entregas', value: 78 } ] },
      { id: 'hs-2', projectId: 'prj-1', at: d(-15), overall: 66, dims: [ { label: 'Cronograma', value: 68 }, { label: 'Custos', value: 85 }, { label: 'Escopo', value: 86 }, { label: 'Riscos', value: 55 }, { label: 'Equipe', value: 68 }, { label: 'Entregas', value: 76 } ] },
      { id: 'hs-3', projectId: 'prj-1', at: d(0), overall: 62, dims: [ { label: 'Cronograma', value: 61 }, { label: 'Custos', value: 83 }, { label: 'Escopo', value: 86 }, { label: 'Riscos', value: 50 }, { label: 'Equipe', value: 64 }, { label: 'Entregas', value: 74 } ] },
      { id: 'hs-4', projectId: 'prj-3', at: d(0), overall: 54, dims: [ { label: 'Cronograma', value: 48 }, { label: 'Custos', value: 66 }, { label: 'Escopo', value: 72 }, { label: 'Riscos', value: 45 }, { label: 'Equipe', value: 60 }, { label: 'Entregas', value: 62 } ] },
      { id: 'hs-5', projectId: 'prj-2', at: d(0), overall: 84, dims: [ { label: 'Cronograma', value: 88 }, { label: 'Custos', value: 91 }, { label: 'Escopo', value: 82 }, { label: 'Riscos', value: 76 }, { label: 'Equipe', value: 80 }, { label: 'Entregas', value: 88 } ] },
      { id: 'hs-6', projectId: 'prj-4', at: d(0), overall: 78, dims: [ { label: 'Cronograma', value: 80 }, { label: 'Custos', value: 90 }, { label: 'Escopo', value: 84 }, { label: 'Riscos', value: 72 }, { label: 'Equipe', value: 68 }, { label: 'Entregas', value: 82 } ] },
      { id: 'hs-7', projectId: 'prj-s1', at: d(0), overall: 86, dims: [ { label: 'Cronograma', value: 88 }, { label: 'Custos', value: 90 }, { label: 'Escopo', value: 85 }, { label: 'Riscos', value: 82 }, { label: 'Equipe', value: 78 }, { label: 'Entregas', value: 88 } ] },
    ],
    insights: [
      { id: 'ai-1', orgId: ORG_PUB, kind: 'Cronograma', severity: 'Crítica', title: 'Tendência de atraso de 18 dias no Projeto Rede', detail: 'Com base no atraso confirmado do fornecedor e na folga consumida do lote 2, a conclusão prevista moveu de +45 para +63 dias.', projectId: 'prj-1', dataUsed: '3 marcos, 6 tarefas, 1 problema ativo, 1 mudança em análise', confidence: 88, createdAt: ts(-1) },
      { id: 'ai-2', orgId: ORG_PUB, kind: 'Recursos', severity: 'Alta', title: 'Sobrecarga sustentada de Marcos Vieira (126%)', detail: 'Alocação acima de 100% há 6 semanas. Tarefas críticas de rede e obra disputam a mesma pessoa.', dataUsed: '2 alocações, 5 tarefas ativas, capacidade 40h/semana', confidence: 93, createdAt: ts(-1) },
      { id: 'ai-3', orgId: ORG_PUB, kind: 'Custos', severity: 'Alta', title: 'Av. Central: realizado 13% acima da linha de base', detail: 'CPI acumulado de 0,89. A mudança MUD-2025-011 (+R$ 210 mil) explica parte do desvio; o restante indica produtividade abaixo do previsto.', projectId: 'prj-3', dataUsed: '4 meses de medições, 1 mudança aprovada', confidence: 90, createdAt: ts(-2) },
      { id: 'ai-4', orgId: ORG_PUB, kind: 'Portfólio', severity: 'Atenção', title: '12 demandas de rede podem ser consolidadas', detail: 'Existe um padrão de demandas correlatas (switches, wi-fi UBS, links de escolas). Consolidar em um Programa de Conectividade geraria economia de escala estimada em 18%.', dataUsed: '3 demandas ativas + histórico de 9 similares', confidence: 74, createdAt: ts(-3) },
      { id: 'ai-5', orgId: ORG_PUB, kind: 'Governança', severity: 'Atenção', title: '4 decisões executivas aguardando há mais de 5 dias', detail: 'Decisões pendentes travam MUD-2025-015, MUD-2025-016 e a consolidação de demandas.', dataUsed: '4 registros no log de decisões', confidence: 99, createdAt: ts(-1) },
    ],
    recommendations: [
      { id: 'rec-1', orgId: ORG_PUB, title: 'Redistribuir tarefas não críticas de Marcos Vieira', detail: 'Mover "Validar redundância de energia do datacenter" para João Pereira libera 30h e reduz a alocação de Marcos para ~112%.', rationale: 'Marcos está com 126% de alocação e concentra 5 tarefas, sendo 4 críticas. João está com 100% e perfil técnico compatível.', projectId: 'prj-1', action: { type: 'reassign', taskId: 'tk-22', userId: 'u-joao' }, status: 'Pendente', createdAt: ts(-1) },
      { id: 'rec-2', orgId: ORG_PUB, title: 'Consolidar demandas de conectividade em programa', detail: 'Unificar DEM-2025-087, DEM-2025-088 e DEM-2025-090 no programa "Cidade Digital" com licitação única de ativos de rede.', rationale: 'As três demandas compartilham categoria, fornecedores e janelas de implantação. O tratamento isolado perde economia de escala (~18%).', action: { type: 'consolidate', demandIds: ['dem-1', 'dem-2', 'dem-3'] }, status: 'Pendente', createdAt: ts(-3) },
      { id: 'rec-3', orgId: ORG_PUB, title: 'Escalonar pendência da concessionária à agência reguladora', detail: 'O remanejamento de posteamento (RSK-004) está sem janela confirmada há 22 dias e bloqueia a frente de calçadas.', rationale: 'O histórico mostra resposta média de 9 dias após acionamento regulatório, contra 30+ dias via canal comercial.', projectId: 'prj-3', action: { type: 'escalate' }, status: 'Pendente', createdAt: ts(-2) },
    ],
    forecasts: [
      { id: 'fc-1', projectId: 'prj-1', generatedAt: ts(-1), forecastEnd: d(63), delayDays: 18, delayProbability: 78, budgetOverrunProbability: 34, healthTrend: 'Piorando', bottlenecks: ['Entrega do fornecedor', 'Capacidade de Marcos Vieira', 'Janelas de migração'] },
      { id: 'fc-2', projectId: 'prj-3', generatedAt: ts(-1), forecastEnd: d(48), delayDays: 18, delayProbability: 71, budgetOverrunProbability: 62, healthTrend: 'Piorando', bottlenecks: ['Posteamento da concessionária', 'Ritmo de pavimentação no período de chuvas'] },
      { id: 'fc-3', projectId: 'prj-2', generatedAt: ts(-1), forecastEnd: d(90), delayDays: 0, delayProbability: 22, budgetOverrunProbability: 8, healthTrend: 'Estável', bottlenecks: ['Credenciais da Fazenda'] },
      { id: 'fc-4', projectId: 'prj-4', generatedAt: ts(-1), forecastEnd: d(140), delayDays: 0, delayProbability: 18, budgetOverrunProbability: 6, healthTrend: 'Melhorando', bottlenecks: [] },
    ],
    alerts: [
      { id: 'al-a1', orgId: ORG_PUB, category: 'Prazo', severity: 'Crítica', message: 'Marco "Núcleo de rede em produção" está 18 dias atrasado.', link: { page: 'projeto', id: 'prj-1', tab: 'cronograma' }, read: false, createdAt: ts(-1, 8) },
      { id: 'al-a2', orgId: ORG_PUB, category: 'Aprovação', severity: 'Alta', message: 'MUD-2025-014 aguarda decisão do sponsor há 7 dias.', link: { page: 'mudancas' }, read: false, createdAt: ts(-1, 9) },
      { id: 'al-a3', orgId: ORG_PUB, category: 'Equipe', severity: 'Alta', message: 'Marcos Vieira em sobrecarga (126%) há 6 semanas.', link: { page: 'recursos' }, read: false, createdAt: ts(-2, 10) },
      { id: 'al-a4', orgId: ORG_PUB, category: 'Custo', severity: 'Atenção', message: 'Av. Central com CPI 0,89 — tendência de estouro de R$ 1,6 mi.', link: { page: 'projeto', id: 'prj-3', tab: 'custos' }, read: false, createdAt: ts(-2, 11) },
      { id: 'al-a5', orgId: ORG_PUB, category: 'IA', severity: 'Atenção', message: 'NEX detectou 3 demandas de rede candidatas à consolidação.', link: { page: 'demandas' }, read: true, createdAt: ts(-3, 14) },
      { id: 'al-a6', orgId: ORG_PUB, category: 'Prazo', severity: 'Atenção', message: '7 tarefas críticas vencem nos próximos 7 dias.', link: { page: 'tarefas' }, read: false, createdAt: ts(0, 7) },
    ],
    notifications: [
      { id: 'nt-1', userId: 'u-mariana', text: 'Novo insight da Inteligência: tendência de atraso no Projeto Rede.', read: false, createdAt: ts(-1, 8) },
      { id: 'nt-2', userId: 'u-mariana', text: 'MUD-2025-014 aguarda análise do comitê.', read: false, createdAt: ts(-1, 9) },
      { id: 'nt-3', userId: 'u-mariana', text: 'Revisão mensal do portfólio em 2 dias.', read: true, createdAt: ts(-2, 16) },
    ],
    audit: [
      { id: 'au-1', orgId: ORG_PUB, userId: 'u-carlos', userName: 'Carlos Lima', at: ts(-1, 17), action: 'ATUALIZOU_PROGRESSO', entity: 'Task', entityId: 'tk-4', before: '58%', after: '62%' },
      { id: 'au-2', orgId: ORG_PUB, userId: 'u-mariana', userName: 'Mariana Souza', at: ts(-1, 15), action: 'GEROU_ANÁLISE_IA', entity: 'AiInsight', after: 'Tendência de atraso — PRJ-2025-001' },
      { id: 'au-3', orgId: ORG_PUB, userId: 'u-fernanda', userName: 'Fernanda Alves', at: ts(-3, 14), action: 'APROVOU_DECISÃO', entity: 'Decision', entityId: 'dc-1', after: 'Migração provisória com switches atuais' },
      { id: 'au-4', orgId: ORG_PUB, userId: 'u-beatriz', userName: 'Beatriz Nunes', at: ts(-7, 11), action: 'CRIOU', entity: 'ChangeRequest', entityId: 'ch-2', after: 'MUD-2025-014' },
      { id: 'au-5', orgId: ORG_PUB, userId: 'u-joao', userName: 'João Pereira', at: ts(-9, 10), action: 'ATUALIZOU_STATUS', entity: 'Demand', entityId: 'dem-1', before: 'Triagem', after: 'Em Análise' },
      { id: 'au-6', orgId: ORG_PUB, userId: 'u-admin', userName: 'Sistema (NEXFROTA)', at: ts(-15, 9), action: 'EVENTO_INTEGRAÇÃO', entity: 'IntegrationEvent', after: 'VEHICLE_REPLACEMENT_REQUIRED → DEM-2025-094' },
    ],
    events: [
      { id: 'ev-1', orgId: ORG_PUB, source: 'NEXFROTA', type: 'VEHICLE_REPLACEMENT_REQUIRED', payload: '6 veículos de fiscalização acima do limite econômico de manutenção', receivedAt: ts(-15, 9), processed: true },
      { id: 'ev-2', orgId: ORG_PUB, source: 'NEXOBRAS', type: 'CONSTRUCTION_PROGRESS_UPDATED', payload: 'Av. Central — medição 08: 71% físico vs 74% planejado', receivedAt: ts(-8, 10), processed: true },
      { id: 'ev-3', orgId: ORG_PUB, source: 'NEXUNITAS', type: 'ORG_DEMAND_SUBMITTED', payload: 'Demanda de capacitação de fiscais de contrato (60 servidores)', receivedAt: ts(-12, 15), processed: true },
      { id: 'ev-4', orgId: ORG_PUB, source: 'NEXSERVICE', type: 'SLA_BREACH_WARNING', payload: 'Portal do Cidadão: disponibilidade 99,1% no mês (meta 99,5%)', receivedAt: ts(-1, 18), processed: false },
    ],
    customFields: [
      { id: 'cf-1', orgId: ORG_PUB, entity: 'Projeto', name: 'Programa Governamental', type: 'Lista' },
      { id: 'cf-2', orgId: ORG_PUB, entity: 'Projeto', name: 'Valor Público Estimado', type: 'Moeda' },
      { id: 'cf-3', orgId: ORG_PUB, entity: 'Demanda', name: 'Política Pública Vinculada', type: 'Texto' },
      { id: 'cf-4', orgId: ORG_PRIV, entity: 'Projeto', name: 'ROI Projetado', type: 'Percentual' },
    ],
  };
}
